
services:
  mysqlPrueba:
    container_name: mysqlPrueba
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: usrPrueba
      MYSQL_PASSWORD: us3rPru3ba
      MYSQL_DATABASE: pruebatecnica
    networks:
      - network-docker
    restart: always
  mcsv-atm:
    container_name: mcsv-atm
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      hostDb: mysqlPrueba
      userDb: usrPrueba
      passwordDb: us3rPru3ba
    networks:
      - network-docker
    depends_on:
      - mysqlPrueba
    restart: always

volumes:
  data-mysql:
    name: data-mysql

networks:
  network-docker:
    name: network-docker
    #solo unicamente windows
    external: true